# Generated by Django 3.0.4 on 2020-06-25 16:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.UUIDField()),
                ('role', models.SmallIntegerField(default=3)),
                ('CollectorName', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=250)),
                ('Password', models.CharField(max_length=100)),
                ('CollectorAddress', models.CharField(max_length=50)),
                ('Pincode', models.IntegerField()),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('hastask', models.IntegerField()),
                ('school', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Collector',
            },
        ),
        migrations.CreateModel(
            name='RepairCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Pincode', models.IntegerField()),
                ('PhoneNumber', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Reapir_Center',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.UUIDField()),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('phonenumber', models.CharField(max_length=10)),
                ('GRNumber', models.CharField(max_length=10)),
                ('classname', models.CharField(max_length=30)),
                ('rollnumber', models.CharField(max_length=10)),
                ('hasphone', models.CharField(default='No', max_length=10)),
                ('school', models.CharField(max_length=50)),
                ('vGRNumber', models.CharField(default=None, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('role', models.SmallIntegerField(default=2)),
                ('avatar', models.ImageField(upload_to='pro_pics')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schoolname', models.CharField(max_length=30)),
                ('schooladdress', models.CharField(max_length=80)),
                ('pincode', models.IntegerField()),
                ('udise', models.CharField(max_length=50)),
                ('principal', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.TextField(max_length=40)),
                ('phonenumber', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('Pincode', models.IntegerField()),
                ('Contact_Number', models.CharField(max_length=10)),
                ('Phone_Company', models.CharField(max_length=50)),
                ('Model_Name', models.CharField(max_length=50)),
                ('Network', models.CharField(choices=[('3G', '3G'), ('4G', '4G')], default=0, max_length=2)),
                ('Camera', models.CharField(choices=[('FrontCamera', 'FrontCamera'), ('BackCamera', 'BackCamera'), ('Front and back', 'Front and back'), ('With Out Camera', 'With Out Camera')], default=0, max_length=15)),
                ('Phone_Rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=50)),
                ('Charger', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=25)),
                ('Earphones', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=30)),
                ('Requires_Repair', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default=1, max_length=40)),
                ('AtService', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=None, max_length=50, null=True)),
                ('ReceivedService', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=None, max_length=50, null=True)),
                ('Collected', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='No', max_length=50, null=True)),
                ('Delivered', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=None, max_length=30, null=True)),
                ('manager', models.UUIDField(null=True)),
                ('AtRepairCenter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.RepairCenter')),
                ('CollectorName', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.Collector')),
                ('GRNumber', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.Student')),
            ],
            options={
                'db_table': 'Phone',
            },
        ),
        migrations.CreateModel(
            name='PhoneStatus',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='public.Phone')),
                ('AtService', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('ReceivedService', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('Collected', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('Delivered', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=30)),
                ('AtRepairCenter', models.ForeignKey(default=None, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.RepairCenter')),
                ('CollectorName', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.Collector')),
                ('GRNumber', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.Student')),
            ],
            options={
                'db_table': 'Phone_status',
            },
        ),
    ]
